version: '2'

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.241.0/24
          gateway: 172.16.241.1

services:
  db:
    image: postgres
    restart: always
    ports:
      - 54321:5432
    environment:
      POSTGRES_PASSWORD: modelmanager
      POSTGRES_USER: modelmanager
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8888
